'use client';
import Link from 'next/link';
import { ActivityEditor, WagonActions, ReleaseForm, CriterionAction, ResolveAction } from './wagon-actions';
import { ancestors } from '@/application/use-cases/commands';
import { isTerminal } from '@/domain/rules';
import { usePlanning } from './planning-provider';
import { selectWagonDetail } from '@/application/use-cases/get-planning';
import { activityLabels, formatDate, formatTimestamp, planningPath, releaseLabels, wagonLabel, wagonPath } from '@/shared/format';
import { Callout, Empty, LoadState, Missing, Panel, Progress, Status } from './ui';
export function WagonDetail({ workId, wagonId }: { workId: string; wagonId: string }) {
  const context = usePlanning();
  if (context.state !== 'ready') return <LoadState error={context.state === 'error'} />;
  const { planning } = context;
  const detail = selectWagonDetail(planning, workId, wagonId);
  if (!detail || !planning.data.users.find(u => u.id === context.actorId)?.workIds.includes(workId)) return <Missing label="Vagão não encontrado nesta obra" href={planningPath(workId)} />;
  const { data } = planning;
  const { wagon, work, sequence, predecessor, successor, activities, criteria, pendingItems, restrictions, debts, releases, history } = detail;
  const person = (id: string) => data.users.find(u => u.id === id)?.name ?? 'Responsável não informado';
  const mandatory = activities.filter(a => a.mandatory);
  const requiredCriteria = criteria.filter(c => c.mandatory);
  const reopenedAncestors = ancestors(data,wagon).filter(w => !isTerminal(w.id,data) && data.history.some(e => e.entityId===w.id && e.action==='terminality_reopened'));
  return <><nav aria-label="Navegação estrutural" className="mb-6 flex flex-wrap gap-2 text-sm"><Link className="text-link" href="/obras">Obras</Link><span aria-hidden="true">/</span><Link className="text-link" href={planningPath(workId)}>{work.name}</Link><span aria-hidden="true">/</span><span>{wagonLabel(wagon.number)}</span></nav>
    <div className="flex flex-wrap items-start justify-between gap-5"><div><p className="eyebrow">{sequence.name}</p><h1 className="page-title">{wagonLabel(wagon.number)}</h1><p className="mt-2 text-lg text-slate-600">{formatDate(wagon.plannedStart)} <span aria-hidden="true">→</span><span className="sr-only">até</span> {formatDate(wagon.plannedEnd)}</p></div><div className="flex flex-wrap items-center gap-3"><Status status={wagon.status}/>{wagon.overdue && <span className="text-sm font-semibold text-rose-700">Takt vencido</span>}</div></div>
    {reopenedAncestors.length>0&&<div className="mt-5"><Callout tone="warning" role="alert">Terminalidade reaberta em período anterior: {reopenedAncestors.map(w=>wagonLabel(w.number)).join(", ")}. Reavalie a liberação e registre as novas pendências.</Callout></div>}<dl className="my-6 grid gap-4 sm:grid-cols-3"><div className="panel p-5"><dt className="text-sm text-slate-600">Duração do takt</dt><dd className="mt-2 text-xl font-semibold">{wagon.taktDays} dias {sequence.calendar === 'calendar_days' ? 'corridos' : 'úteis'}</dd></div><div className="panel p-5"><dt className="text-sm text-slate-600">Progresso ponderado</dt><dd className="mt-3"><Progress value={wagon.progress} label="Progresso do vagão" /></dd></div><div className="panel p-5"><dt className="text-sm text-slate-600">Responsáveis pelo período</dt><dd className="mt-2 font-semibold">{wagon.responsibleIds.map(person).join(', ') || 'Não informado'}</dd></div></dl>
    <nav aria-label="Sequência de vagões" className="mb-6 grid gap-3 sm:grid-cols-2">{[{ label: '← Vagão anterior', value: predecessor, empty: 'Primeiro vagão da sequência' }, { label: 'Vagão seguinte →', value: successor, empty: 'Último vagão planejado' }].map(item => <div className="panel p-4" key={item.label}><p className="mb-2 text-sm text-slate-600">{item.label}</p>{item.value ? <Link className="text-link" href={wagonPath(workId, item.value.id)}>{wagonLabel(item.value.number)} · {formatDate(item.value.plannedStart)} a {formatDate(item.value.plannedEnd)}</Link> : <p className="text-sm text-slate-500">{item.empty}</p>}</div>)}</nav>
    <WagonActions workId={workId} wagonId={wagonId}/><section className="panel mb-6 overflow-hidden" aria-labelledby="activities-title"><div className="border-b border-slate-200 p-5"><h2 id="activities-title" className="text-lg font-semibold">Atividades do período</h2><p className="mt-1 text-sm text-slate-600">Os locais pertencem às atividades. Um mesmo vagão pode reunir diferentes pavimentos e zonas.</p></div>{activities.length === 0 ? <div className="p-5"><Empty>Nenhuma atividade neste período. O vagão ainda não pode ser terminal.</Empty></div> : <div className="overflow-x-auto" role="region" aria-label="Atividades do período" tabIndex={0}><table className="data-table min-w-[1050px]"><thead><tr>{['Atividade / local', 'Responsável', 'Previsão', 'Progresso', 'Status', 'Peso / origem'].map(label => <th scope="col" key={label}>{label}</th>)}</tr></thead><tbody>{activities.map(activity => <tr key={activity.id}><th scope="row" className="min-w-64"><p>{activity.name}</p><p className="mt-1 font-normal text-slate-600">{data.locations.find(l => l.id === activity.locationId)?.name ?? 'Local não informado'}</p><p className="mt-1 font-normal text-slate-500">{activity.mandatory ? 'Obrigatória' : 'Opcional'}</p></th><td>{person(activity.responsibleId)}</td><td className="whitespace-nowrap">{formatDate(activity.plannedStart)}<br/>a {formatDate(activity.plannedEnd)}</td><td><Progress value={activity.progress} label={`Progresso de ${activity.name}`} /></td><td>{activityLabels[activity.status]}</td><td>{activity.weight}<br/><span className="text-slate-500">{{ manual: 'Manual', mock: 'Demonstração', prevision: 'Prevision' }[activity.origin]}</span><div className="mt-3 min-w-64"><ActivityEditor key={activity.updatedAt} workId={workId} activity={activity}/></div></td></tr>)}</tbody></table></div>}</section>
    <div className="grid gap-6 lg:grid-cols-2"><Panel title="Terminalidade"><p className="text-sm leading-6 text-slate-600">{mandatory.filter(a => a.progress === 100 && a.status === 'completed').length} de {mandatory.length} atividades obrigatórias concluídas · {requiredCriteria.filter(c => c.fulfilled).length} de {requiredCriteria.length} critérios obrigatórios atendidos.</p>{criteria.length === 0 ? <div className="mt-4"><Empty>Nenhum critério adicional cadastrado.</Empty></div> : <ul className="mt-4 space-y-4">{criteria.map(c => <li key={c.id} className="rounded-[var(--radius-sm)] border border-[var(--border)] bg-[var(--bg)] p-4"><p className="font-medium">{c.fulfilled ? 'Atendido' : 'Aguardando'} · {c.description}</p><p className="mt-1 text-sm text-[var(--ink-muted)]">{activities.find(a => a.id === c.activityId)?.name} · {c.mandatory ? 'Obrigatório' : 'Opcional'}</p>{c.fulfilled && c.confirmedBy && c.confirmedAt && <p className="mt-1 text-sm text-[var(--ink-muted)]">Confirmado por {person(c.confirmedBy)} em {formatTimestamp(c.confirmedAt)}</p>}<CriterionAction id={c.id} fulfilled={c.fulfilled}/></li>)}</ul>}<p className={`mt-4 text-sm font-medium ${wagon.status === 'terminal' ? 'text-[var(--success-ink)]' : 'text-[var(--ink-muted)]'}`}>{wagon.status === 'terminal' ? 'Este vagão atende às condições de terminalidade.' : 'Este vagão ainda não atende a todas as condições de terminalidade.'}</p></Panel>
    <Panel title="Liberação deste vagão">{releases.length === 0 ? <Empty>Aguardando liberação para iniciar a execução.</Empty> : releases.map(release => <div key={release.id} className="space-y-3"><p className="font-semibold">Liberação {releaseLabels[release.type].toLowerCase()}</p><p className="text-sm text-slate-600">Autorizada por {person(release.authorizedBy)} em {formatTimestamp(release.releasedAt)}.</p>{release.justification && <p className="text-sm leading-6">{release.justification}</p>}{release.regularizationResponsibleId && <p className="text-sm">Regularização: {person(release.regularizationResponsibleId)}{release.dueDate && ` · até ${formatDate(release.dueDate)}`}</p>}{release.acceptedPendingIds.length > 0 && <ul className="space-y-2 text-sm">{release.acceptedPendingIds.map(id => <li key={id}>Pendência aceita: {data.pendingItems.find(p => p.id === id)?.description ?? 'Registro indisponível'}</li>)}</ul>}</div>)}<ReleaseForm workId={workId} wagonId={wagonId}/><p className="mt-4 text-sm text-slate-500">A liberação não altera a terminalidade do vagão anterior.</p></Panel>
    <Panel title="Pendências deste vagão">{pendingItems.length === 0 ? <Empty>Nenhuma pendência registrada.</Empty> : <ul className="space-y-4">{pendingItems.map(p => <li key={p.id}><p className="font-medium">{p.description}</p><p className="mt-1 text-sm text-slate-600">{person(p.responsibleId)} · prazo {formatDate(p.dueDate)}</p><p className="mt-1 text-sm">{p.status === 'resolved' ? 'Resolvida' : 'Aberta'}{p.status === 'open' && p.dueDate < planning.today ? ' · Vencida' : ''}{p.blocksTerminality ? ' · Bloqueia terminalidade' : ''}</p>{p.status==='open'&&<ResolveAction id={p.id} kind="pending"/>}</li>)}</ul>}</Panel>
    <Panel title="Restrições">{restrictions.length === 0 ? <Empty>Nenhuma restrição registrada.</Empty> : <ul className="space-y-4">{restrictions.map(r => <li key={r.id}><p className="font-medium">{r.description}</p><p className="mt-1 text-sm text-slate-600">{person(r.responsibleId)} · prazo {formatDate(r.dueDate)}</p><p className="mt-1 text-sm">{r.status === 'open' ? 'Aberta' : 'Resolvida'}{r.blocksExecution ? ' · Bloqueia execução' : ''}{r.blocksTerminality ? ' · Bloqueia terminalidade' : ''}</p>{r.status==='open'&&<ResolveAction id={r.id} kind="restriction"/>}</li>)}</ul>}</Panel>
    <Panel title="Dívidas de terminalidade">{debts.length === 0 ? <Empty>Nenhuma dívida deste vagão ou de seus antecessores.</Empty> : <ul className="space-y-5">{debts.map(debt => {
      const pending = data.pendingItems.find(p => p.id === debt.pendingItemId)!;
      const origin = data.wagons.find(w => w.id === pending.wagonId)!;
      const release = data.releases.find(r => r.id === debt.releaseId)!;
      const releasedWagon = data.wagons.find(w => w.id === release.wagonId)!;
      return <li key={debt.id} className="callout callout-warning"><p className="font-medium">{pending.description}</p><p className="mt-2 text-sm">Origem: <Link className="text-link" href={wagonPath(workId, origin.id)}>{wagonLabel(origin.number)}</Link> · {origin.id === wagon.id ? 'Dívida própria' : 'Herdada de período anterior'}</p><p className="mt-1 text-sm">Gerada na liberação de <Link className="text-link" href={wagonPath(workId, releasedWagon.id)}>{wagonLabel(releasedWagon.number)}</Link>.</p><p className="mt-1 text-sm">{person(debt.responsibleId)} · prazo {formatDate(debt.dueDate)}</p><p className="mt-2 text-sm font-semibold">{pending.status === 'resolved' ? 'Resolvida' : debt.dueDate < planning.today ? 'Aberta · Vencida' : 'Aberta'}</p></li>;
    })}</ul>}</Panel>
    <Panel title="Histórico">{history.length === 0 ? <Empty>Nenhum evento registrado para este vagão.</Empty> : <ol className="space-y-4">{history.map(event => <li key={event.id}><p className="font-medium">{({exceptional_release:'Liberação excepcional registrada',release:'Liberação registrada',create_activity:'Atividade adicionada',update_activity:'Atividade atualizada',create_criterion:'Critério adicionado',set_criterion:'Critério atualizado',create_pending:'Pendência registrada',resolve_pending:'Pendência resolvida',create_restriction:'Restrição registrada',resolve_restriction:'Restrição resolvida',edit_wagon:'Período atualizado',create_wagon:'Vagão criado',terminality_reopened:'Terminalidade reaberta',import_activities:'Atividades importadas do Prevision'} as Record<string,string>)[event.action]??'Planejamento atualizado'}</p><p className="mt-1 text-sm text-slate-600">{person(event.authorId)} · {formatTimestamp(event.occurredAt)}</p>{typeof event.changes.reason==='string'&&event.changes.reason&&<p className="mt-1 text-sm">Justificativa: {event.changes.reason}</p>}{typeof event.changes.resolution==='string'&&<p className="mt-1 text-sm">Resolução: {event.changes.resolution}</p>}</li>)}</ol>}</Panel></div>
    <Link href={planningPath(workId)} className="text-link mt-8 inline-block">← Voltar ao planejamento da obra</Link>
  </>;
}
