'use client';
import type { Activity } from '@/domain/entities';
import { assessRelease } from '@/application/use-cases/commands';
import { usePlanning } from './planning-provider';
import { Check, CommandForm, Field, Reason, Responsible, TextField, checked, number, value } from './forms';
const activityInput = (d: FormData) => ({name:value(d,'name'),locationId:value(d,'locationId'),responsibleId:value(d,'responsibleId'),plannedStart:value(d,'plannedStart'),plannedEnd:value(d,'plannedEnd'),weight:number(d,'weight'),mandatory:checked(d,'mandatory')});
function ActivityFields({ workId, start, end, activity }: {workId:string;start:string;end:string;activity?:Activity}) {
  const c = usePlanning(); if (c.state !== 'ready') return null;
  return <><TextField name="name" label="Atividade" defaultValue={activity?.name}/><Field label="Local da atividade"><select name="locationId" className="field" required defaultValue={activity?.locationId}><option value="">Selecione</option>{c.planning.data.locations.filter(l => l.workId === workId).map(l => <option key={l.id} value={l.id}>{l.name}</option>)}</select></Field><Responsible workId={workId} defaultValue={activity?.responsibleId}/><div className="grid gap-3 sm:grid-cols-2"><TextField name="plannedStart" label="Início previsto" type="date" defaultValue={activity?.plannedStart ?? start} min={start} max={end}/><TextField name="plannedEnd" label="Término previsto" type="date" defaultValue={activity?.plannedEnd ?? end} min={start} max={end}/></div><TextField name="weight" label="Peso no progresso" type="number" min={0.01} step="any" defaultValue={activity?.weight ?? 1}/><Check name="mandatory" label="Obrigatória para terminalidade" defaultChecked={activity?.mandatory ?? true}/><Reason/></>;
}
export function ActivityEditor({ workId, activity }: {workId:string;activity:Activity}) {
  const c = usePlanning(); if (c.state !== 'ready') return null; const wagon = c.planning.data.wagons.find(w => w.id === activity.wagonId)!;
  return <CommandForm title="Atualizar atividade" command={d => ({type:'update_activity',activityId:activity.id,activity:activityInput(d),progress:number(d,'progress'),status:value(d,'status') as Activity['status'],reason:value(d,'reason')})}><ActivityFields workId={workId} start={wagon.plannedStart} end={wagon.plannedEnd} activity={activity}/><TextField name="progress" label="Progresso (%)" type="number" min={0} max={100} step="any" defaultValue={activity.progress}/><Field label="Status"><select className="field" name="status" defaultValue={activity.status}><option value="not_started">Não iniciada</option><option value="in_progress">Em andamento</option><option value="completed">Concluída</option></select></Field></CommandForm>;
}
export function WagonActions({workId,wagonId}:{workId:string;wagonId:string}) {
  const c = usePlanning(); if (c.state !== 'ready') return null; const {data}=c.planning;
  const wagon=data.wagons.find(w=>w.id===wagonId)!; const activities=data.activities.filter(a=>a.wagonId===wagonId);
  const selectActivity = <Field label="Atividade vinculada"><select className="field" name="activityId"><option value="">Todo o vagão</option>{activities.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></Field>;
  return <div className="my-6 grid items-start gap-4 lg:grid-cols-2"><CommandForm title="Adicionar atividade ao período" command={d=>({type:'create_activity',wagonId,activity:activityInput(d),reason:value(d,'reason')})}><ActivityFields workId={workId} start={wagon.plannedStart} end={wagon.plannedEnd}/></CommandForm>
  <CommandForm title="Adicionar critério de terminalidade" command={d=>({type:'create_criterion',activityId:value(d,'activityId'),description:value(d,'description'),mandatory:checked(d,'mandatory'),reason:value(d,'reason')})}><Field label="Atividade"><select className="field" name="activityId" required><option value="">Selecione</option>{activities.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></Field><TextField name="description" label="Critério de aceite"/><Check name="mandatory" label="Obrigatório" defaultChecked/><Reason/></CommandForm>
  <CommandForm title="Registrar pendência" command={d=>({type:'create_pending',wagonId,activityId:value(d,'activityId')||undefined,description:value(d,'description'),responsibleId:value(d,'responsibleId'),dueDate:value(d,'dueDate'),blocksTerminality:checked(d,'blocksTerminality'),reason:value(d,'reason')})}><TextField name="description" label="Pendência"/>{selectActivity}<Responsible workId={workId}/><TextField name="dueDate" label="Prazo" type="date"/><Check name="blocksTerminality" label="Bloqueia terminalidade" defaultChecked/><Reason/></CommandForm>
  <CommandForm title="Registrar restrição" command={d=>({type:'create_restriction',wagonId,activityId:value(d,'activityId')||undefined,description:value(d,'description'),responsibleId:value(d,'responsibleId'),dueDate:value(d,'dueDate'),blocksTerminality:checked(d,'blocksTerminality'),blocksExecution:checked(d,'blocksExecution'),reason:value(d,'reason')})}><TextField name="description" label="Restrição"/>{selectActivity}<Responsible workId={workId}/><TextField name="dueDate" label="Prazo" type="date"/><Check name="blocksTerminality" label="Bloqueia terminalidade" defaultChecked/><Check name="blocksExecution" label="Bloqueia execução" defaultChecked/><Reason/></CommandForm>
  {!data.releases.some(r=>r.wagonId===wagonId)&&<CommandForm title="Editar período e responsável" command={d=>({type:'edit_wagon',wagonId,plannedStart:value(d,'plannedStart'),plannedEnd:value(d,'plannedEnd'),responsibleId:value(d,'responsibleId')})}><TextField name="plannedStart" label="Marco inicial" type="date" defaultValue={wagon.plannedStart}/><TextField name="plannedEnd" label="Marco final" type="date" defaultValue={wagon.plannedEnd}/><Responsible workId={workId} defaultValue={wagon.responsibleIds[0]}/></CommandForm>}</div>;
}
export function ReleaseForm({workId,wagonId}:{workId:string;wagonId:string}) {
  const c=usePlanning();if(c.state!=='ready')return null;
  const {data}=c.planning;const assessment=assessRelease(data,wagonId);
  if(data.releases.some(r=>r.wagonId===wagonId))return null;
  const mode=!assessment.previous?'initial':assessment.normal?'normal':'exceptional';
  return <div className="mt-4">{assessment.restrictions.length>0&&<p className="mb-3 text-sm text-rose-800">Restrições impeditivas: {assessment.restrictions.map(r=>r.description).join('; ')}.</p>}{assessment.uncovered.length>0&&<p className="mb-3 text-sm text-amber-900">Condições ainda sem pendência registrada: {assessment.uncovered.join('; ')}.</p>}{assessment.pending.length>0&&<ul className="mb-4 space-y-2 text-sm">{assessment.pending.map(p=><li key={p.id}>Pendência a aceitar: {p.description}</li>)}</ul>}<CommandForm title={`Liberar vagão (${mode==='initial'?'inicial':mode==='normal'?'normal':'excepcional'})`} submit="Registrar liberação" command={d=>({type:'release',wagonId,mode,justification:value(d,'justification'),responsibleId:value(d,'responsibleId'),dueDate:value(d,'dueDate')})}>{mode==='exceptional'?<><TextField name="justification" label="Justificativa da liberação excepcional"/><Responsible workId={workId}/><TextField name="dueDate" label="Prazo futuro de regularização" type="date"/><p className="text-sm text-slate-600">Todas as pendências listadas serão registradas nesta autorização. Dívidas anteriores preservam o prazo originalmente assumido.</p></>:<p className="text-sm">A liberação será registrada em seu nome.</p>}</CommandForm></div>;
}
export function CriterionAction({id,fulfilled}:{id:string;fulfilled:boolean}) {return <div className="mt-3"><CommandForm title={fulfilled?'Reabrir critério':'Confirmar critério'} command={d=>({type:'set_criterion',criterionId:id,fulfilled:!fulfilled,reason:value(d,'reason')})}>{fulfilled?<Reason/>:<p className="text-sm">Confirme que o critério foi atendido.</p>}</CommandForm></div>;}
export function ResolveAction({id,kind}:{id:string;kind:'pending'|'restriction'}) {return <div className="mt-3"><CommandForm title="Registrar resolução" command={d=>kind==='pending'?{type:'resolve_pending',pendingId:id,resolution:value(d,'resolution')}:{type:'resolve_restriction',restrictionId:id,resolution:value(d,'resolution')}}><TextField name="resolution" label="Como foi resolvido?"/></CommandForm></div>;}
