'use client';
import Link from 'next/link';
import { useState } from 'react';
import { usePlanning } from '@/modules/planejamento/planning-provider';
import { Field } from '@/modules/planejamento/forms';
import { Empty, LoadState } from '@/modules/planejamento/ui';
import { formatDate, wagonLabel, wagonPath } from '@/shared/format';
import type { ImportedActivity } from '@/application/use-cases/commands';
export function PrevisionIntegration() {
  const c=usePlanning();
  const [search,setSearch]=useState('');
  const [projects,setProjects]=useState<{id:string;name:string}[]>([]);
  const [projectId,setProjectId]=useState('');const [loadedProjectId,setLoadedProjectId]=useState('');
  const [rows,setRows]=useState<ImportedActivity[]>([]);const [skipped,setSkipped]=useState(0);
  const [selected,setSelected]=useState<string[]>([]);const [wagonId,setWagonId]=useState('');const [responsibleId,setResponsibleId]=useState('');
  const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [message,setMessage]=useState('');const [reason,setReason]=useState('');
  if(c.state!=='ready')return <LoadState error={c.state==='error'}/>;
  const {data}=c.planning;const actor=data.users.find(u=>u.id===c.actorId)!;
  const allowedSequences=data.sequences.filter(s=>actor.workIds.includes(s.workId));
  const wagons=data.wagons.filter(w=>allowedSequences.some(s=>s.id===w.sequenceId));
  const wagon=wagons.find(w=>w.id===wagonId);const workId=allowedSequences.find(s=>s.id===wagon?.sequenceId)?.workId;
  const canImport=actor.role!=='viewer';
  const visibleRows=rows.filter(r=>`${r.name} ${r.location}`.toLocaleLowerCase('pt-BR').includes(search.toLocaleLowerCase('pt-BR')));
  const linkedWork=data.works.find(w=>w.previsionProjectId===projectId);
  const eligible=(row:ImportedActivity)=>!!wagon&&row.plannedStart>=wagon.plannedStart&&row.plannedEnd<=wagon.plannedEnd&&!data.activities.some(a=>a.previsionExternalId===`${loadedProjectId}:${row.externalId}`);
  async function query(kind:'projects'|'activities') {
    setBusy(true);setError('');setMessage('');
    try {
      const response=await fetch(kind==='projects'?'/api/prevision':`/api/prevision?projectId=${encodeURIComponent(projectId)}`);
      const result=await response.json();if(!response.ok)throw new Error(result.error??'Falha na consulta.');
      if(kind==='projects'){setProjects(result.projects);setMessage(`${result.projects.length} obras encontradas.`);}else{setRows(result.rows);setSkipped(result.skipped);setLoadedProjectId(projectId);setSelected([]);setMessage(`${result.rows.length} atividades disponíveis para revisão.`);}
    }catch(e){setError(e instanceof Error?e.message:'Não foi possível consultar o Prevision.');}finally{setBusy(false);}
  }
  return <><Link className="text-link text-sm" href="/obras">← Obras</Link><p className="eyebrow mt-6">Integração</p><h1 className="page-title">Prevision</h1><p className="mt-2 max-w-3xl text-slate-600">Consulte as obras, revise as atividades e escolha o vagão de destino. A importação não altera dados no Prevision.</p><div className="panel mt-6 p-5"><div className="grid items-end gap-4 md:grid-cols-3"><button className="button" disabled={busy} onClick={()=>query('projects')}>Consultar obras do Prevision</button><Field label="Obra no Prevision"><select className="field" value={projectId} disabled={busy} onChange={e=>{setProjectId(e.target.value);setLoadedProjectId('');setRows([]);setSelected([]);}}><option value="">Selecione uma obra</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></Field><button className="button" disabled={busy||!projectId} onClick={()=>query('activities')}>{busy?'Consultando…':'Consultar atividades'}</button></div><div className="mt-4">{projectId&&(linkedWork?<Link className="text-link" href={`/obras/${linkedWork.id}/planejamento`}>Abrir obra vinculada →</Link>:actor.role==='manager'&&<button className="button" disabled={busy} onClick={async()=>{setBusy(true);setError('');try{const project=projects.find(p=>p.id===projectId)!;await c.execute({type:'create_work',name:project.name,code:`PRV-${projectId}`,previsionProjectId:projectId});setMessage('Obra local criada. Abra o planejamento para cadastrar a sequência e os períodos.');}catch(e){setError(e instanceof Error?e.message:'Não foi possível criar a obra.');}finally{setBusy(false);}}}>Criar obra local deste projeto</button>)}</div><p className="mt-3 text-sm text-slate-500">Aguarde ao menos 11 segundos entre consultas. Resultados são reutilizados por um minuto.</p></div>
  <div className="panel mt-6 p-5"><h2 className="mb-4 text-lg font-semibold">Destino da importação</h2><div className="grid gap-4 md:grid-cols-2"><Field label="Vagão / período"><select className="field" value={wagonId} onChange={e=>{setWagonId(e.target.value);setSelected([]);setResponsibleId('');}}><option value="">Selecione</option>{wagons.map(w=><option key={w.id} value={w.id}>{data.works.find(o=>o.id===allowedSequences.find(s=>s.id===w.sequenceId)?.workId)?.name} · {wagonLabel(w.number)} · {formatDate(w.plannedStart)} a {formatDate(w.plannedEnd)}</option>)}</select></Field><Field label="Responsável local pelas atividades"><select className="field" value={responsibleId} onChange={e=>setResponsibleId(e.target.value)}><option value="">Selecione</option>{data.users.filter(u=>workId&&u.workIds.includes(workId)).map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select></Field></div><p className="mt-3 text-sm leading-6 text-slate-600">Somente atividades inteiramente dentro do período podem ser selecionadas. Atividades que atravessam vários vagões precisam ter seu planejamento revisto antes da importação. O peso inicial será 1; todas terão um critério de conferência local pendente.</p></div>
  {loadedProjectId&&<section className="panel mt-6 overflow-hidden" aria-labelledby="import-title"><h2 id="import-title" className="p-5 text-lg font-semibold">Revisar atividades · {rows.length}</h2><div className="flex flex-wrap items-end gap-4 px-5 pb-5"><Field label="Buscar atividade ou local"><input className="field" value={search} onChange={e=>setSearch(e.target.value)}/></Field>{canImport&&<button className="button" disabled={busy||!wagon} onClick={()=>setSelected(visibleRows.filter(eligible).map(r=>r.externalId))}>Selecionar elegíveis da busca</button>}</div>{visibleRows.length===0?<div className="p-5"><Empty>Nenhuma atividade válida nesta obra.</Empty></div>:<div className="max-h-[550px] overflow-auto" tabIndex={0} role="region" aria-label="Atividades para importação"><table className="data-table min-w-[850px]"><thead><tr><th scope="col">Importar</th><th scope="col">Atividade / local</th><th scope="col">Previsão</th><th scope="col">Progresso</th><th scope="col">Elegibilidade</th></tr></thead><tbody>{visibleRows.map(row=>{const imported=data.activities.some(a=>a.previsionExternalId===`${loadedProjectId}:${row.externalId}`);return <tr key={row.externalId}><td><input type="checkbox" aria-label={`Importar ${row.name} em ${row.location}`} checked={selected.includes(row.externalId)} disabled={!eligible(row)||busy||!canImport} onChange={e=>setSelected(ids=>e.target.checked?[...ids,row.externalId]:ids.filter(id=>id!==row.externalId))}/></td><th scope="row">{row.name}<p className="font-normal text-slate-600">{row.location}</p></th><td className="whitespace-nowrap">{formatDate(row.plannedStart)}<br/>a {formatDate(row.plannedEnd)}</td><td>{row.progress}%</td><td>{imported?'Já importada':!wagon?'Escolha um vagão':eligible(row)?'Dentro do período':'Fora do período'}</td></tr>;})}</tbody></table></div>}{skipped>0&&<p className="px-5 py-3 text-sm text-amber-900">{skipped} registros não puderam ser importados por falta de dados válidos. Nenhuma data ou progresso foi presumido.</p>}</section>}
  {canImport&&<div className="mt-5 space-y-4"><Field label="Justificativa (necessária se o vagão já estiver terminal)"><input className="field" value={reason} onChange={e=>setReason(e.target.value)}/></Field><button className="button" disabled={busy||!selected.length||!responsibleId||!wagonId} onClick={async()=>{setBusy(true);setError('');setMessage('');try{const chosen=rows.filter(r=>selected.includes(r.externalId));if(chosen.some(r=>!eligible(r)))throw new Error('Revise as atividades selecionadas.');await c.execute({type:'import_activities',wagonId,projectId:loadedProjectId,responsibleId,rows:chosen,reason});setSelected([]);setMessage(`${chosen.length} atividades importadas. A conferência de terminalidade permanece pendente.`);}catch(e){setError(e instanceof Error?e.message:'Não foi possível importar.');}finally{setBusy(false);}}}>Importar {selected.length} atividades selecionadas</button>{wagon&&workId&&<Link className="text-link ml-4" href={wagonPath(workId,wagonId)}>Abrir vagão →</Link>}</div>}
  {error&&<p role="alert" className="mt-4 rounded-lg bg-rose-50 p-4 text-sm text-rose-800">{error}</p>}{message&&<p role="status" className="mt-4 rounded-lg bg-green-50 p-4 text-sm text-green-800">{message}</p>}
  </>;
}
